name: flutter_application
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  fluttertoast: ^8.2.6
  another_carousel_pro: ^1.0.2
  carousel_slider: ^5.0.0
  qr_code_scanner: ^1.0.1
  url_launcher: ^6.3.0
  local_auth: ^2.3.0
  gap: ^3.0.1
  video_player: ^2.9.2
  audioplayers: ^6.1.0
  file_picker: ^8.1.2
  flick_video_player: ^0.9.0
  youtube_player_flutter: ^9.1.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/Gymbox_Images/
    - assets/audios/
    - assets/taxi/
